# Generated by Django 4.2.3 on 2023-07-27 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='content_arabic',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
